name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: mobiltracker
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        env:
          GITHUB_REF: ${{ github.ref }}
        with:
          context: .
          push: true
          tags: |
            mobiltracker/prometheus-mssql-exporter:latest
            mobiltracker/prometheus-mssql-exporter:${GITHUB_REF#refs/tags/}
